token: "kBPIDfNdSfk8fkATerBa6ct6yshdPbOX"
basePath: "http://api.pripoj.me"
serverPort: 8082
devEUIs:
- "0004A30B0019D0EA"
cutData:
- start: 2016-10-26
  devEUIs:
  - "0004A30B0019D0EA"
mockData:
- start: 2016-10-01
  devEUIs:
  - "0004A30B0019D0EB"