token: "kBPIDfNdSfk8fkATerBa6ct6yshdPbOX"
basePath: "http://api.pripoj.me"
serverPort: 8082
devEUIs:
- "0004A30B0019D0EA"
cutData:
- data:
    start: 2016-10-25
    devEUIs: 
    - "0004A30B0019D0EA"