platform: linux

image_resource:
  type: docker-image
  source: {repository: node,
           tag: onbuild           
          }

inputs:
- name: source
- name: binaries

outputs:
- name: package

run:
    path: ls
    args: ["../source/ci/tasks/"]
    dir: ./binaries