platform: linux

image_resource:
  type: docker-image
  source: {repository: node,
           tag: onbuild           
          }

inputs:
- name: source
- name: binaries

outputs:
- name: package

run:
    path: sh
    args: ["./ci/tasks/pack.sh"]
    dir: ./source