platform: linux

image_resource:
  type: docker-image
  source: {repository: node,
           tag: onbuild           
          }

inputs:
- name: source
- name: binaries

outputs:
- name: package

run:
    path: sh
    args:
      - -exc
      - |
        pwd
        ls -l
        cd binaries
        pwd
        ls -l
        ls -l ../source/ci/tasks/
        sh ../source/ci/tasks/build.sh