platform: linux

image_resource:
  type: docker-image
  source: {repository: node,
           tag: onbuild           
          }

inputs:
- name: binaries

outputs:
- name: package

run:
    path: sh
    args:
      - -exc
      - |
        ls -l
        cd binaries
        pwd
        ls -l
        tar -cf ../package/binaries.tar ./
        ls -l ../package
        tar -tvf ../package/binaries.tar