platform: linux

image_resource:
  type: docker-image
  source: {repository: node,
           tag: onbuild           
          }

inputs:
- name: iot-lora-cra-cache

outputs:
- name: binaries

run:
    path: ls
    args: ["-l"]
    #path: sh
    #args: ["./ci/build.sh"]
    #dir: ./iot-lora-cra-cache