platform: linux

image_resource:
  type: docker-image
  source: {repository: node,
           tag: onbuild           
          }

inputs:
- name: source

outputs:
- name: binaries

run:
    path: sh
    args: ["./ci/build.sh"]
    dir: ./source