resources:
- name: iot-lora-cra-cache-registry
  type: docker-image
  source:
    repository: hndocker.oksystem.local:40003/iot/iot-lora-cra-cache
    username: kacis
    password: {{docker-registry-password}}
    ca_certs:
    - domain: hndocker.oksystem.local:443
      cert: | 
        -----BEGIN CERTIFICATE-----
        MIIDXjCCAkYCCQCeUULdHyEEdjANBgkqhkiG9w0BAQUFADBxMQswCQYDVQQGEwJD
        WjEXMBUGA1UECAwOQ3plY2ggUmVwdWJsaWMxDzANBgNVBAcMBlByYWd1ZTEWMBQG
        A1UECgwNT0tzeXN0ZW0gYS5zLjEgMB4GA1UEAwwXaG5kb2NrZXIub2tzeXN0ZW0u
        bG9jYWwwHhcNMTYwNzA4MDgxMjAxWhcNMjYwNzA2MDgxMjAxWjBxMQswCQYDVQQG
        EwJDWjEXMBUGA1UECAwOQ3plY2ggUmVwdWJsaWMxDzANBgNVBAcMBlByYWd1ZTEW
        MBQGA1UECgwNT0tzeXN0ZW0gYS5zLjEgMB4GA1UEAwwXaG5kb2NrZXIub2tzeXN0
        ZW0ubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDB0zGAka/W
        jMvOLutiKDE8MXw2KI5ulAx6wgo4juPwQ2UPQx+Oh3EFJ3czuXL4C3MwQnnryqD7
        62XJe1qIuisj5NcUeHNWW+bj6bZyPmRi3bCsmIZky42mShTrVm1wtcwfNZykvyer
        tbkPfoN6NCDXErOzqMfo+yhRssIhQe9WyB78idJeywX2iE/ur+X9l2Oy91l65yIQ
        //qebcHqN8QDtB9Hk7T31SqK/+mZN/Qnjw5VASofE3McpOGeHA7xUF1dQ4E8CCA5
        srWisSDoJUZEvS5SrzdBGF2szMK0G7ZVxhHkWmUHlgN5dxjGNH7lS2DC6sX7H+Vf
        mh/iSPRbLPiFAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAJgZJEKZMtqpcxEhOELU
        VmM5HpsG++Q+oTQzmM0HZeYRAJ6nSkCa7aN6WJHblv3Kew6/9kgum9U2szc3/Ouc
        hmO/Hw/hGt7gssrIt6yFe0a0oXhwbFnN6KM1xtek9zwkXnHxV2fOBro77+sGJkQ9
        Y50RRNYROSEgsndO9xSQa8yfqgwfGy9orQwP6SBDsY8fT9KuZza5CiwZ0utig9l7
        HaRynY3jm7/K1Du5xLjZ/+Hoji76vjAqogIJv/FXFrqXjcJMt1bZcrkxPsZfWHgg
        uMOUZV4WjEv+MCo3sVavPgtS9oscZw9hVlMBAcF42L/F1CkdAT1g0BIaj8gw7U9N
        pMI=
        -----END CERTIFICATE-----
    - domain: hndocker.oksystem.local:40003
      cert: | 
        -----BEGIN CERTIFICATE-----
        MIIDXjCCAkYCCQCeUULdHyEEdjANBgkqhkiG9w0BAQUFADBxMQswCQYDVQQGEwJD
        WjEXMBUGA1UECAwOQ3plY2ggUmVwdWJsaWMxDzANBgNVBAcMBlByYWd1ZTEWMBQG
        A1UECgwNT0tzeXN0ZW0gYS5zLjEgMB4GA1UEAwwXaG5kb2NrZXIub2tzeXN0ZW0u
        bG9jYWwwHhcNMTYwNzA4MDgxMjAxWhcNMjYwNzA2MDgxMjAxWjBxMQswCQYDVQQG
        EwJDWjEXMBUGA1UECAwOQ3plY2ggUmVwdWJsaWMxDzANBgNVBAcMBlByYWd1ZTEW
        MBQGA1UECgwNT0tzeXN0ZW0gYS5zLjEgMB4GA1UEAwwXaG5kb2NrZXIub2tzeXN0
        ZW0ubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDB0zGAka/W
        jMvOLutiKDE8MXw2KI5ulAx6wgo4juPwQ2UPQx+Oh3EFJ3czuXL4C3MwQnnryqD7
        62XJe1qIuisj5NcUeHNWW+bj6bZyPmRi3bCsmIZky42mShTrVm1wtcwfNZykvyer
        tbkPfoN6NCDXErOzqMfo+yhRssIhQe9WyB78idJeywX2iE/ur+X9l2Oy91l65yIQ
        //qebcHqN8QDtB9Hk7T31SqK/+mZN/Qnjw5VASofE3McpOGeHA7xUF1dQ4E8CCA5
        srWisSDoJUZEvS5SrzdBGF2szMK0G7ZVxhHkWmUHlgN5dxjGNH7lS2DC6sX7H+Vf
        mh/iSPRbLPiFAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAJgZJEKZMtqpcxEhOELU
        VmM5HpsG++Q+oTQzmM0HZeYRAJ6nSkCa7aN6WJHblv3Kew6/9kgum9U2szc3/Ouc
        hmO/Hw/hGt7gssrIt6yFe0a0oXhwbFnN6KM1xtek9zwkXnHxV2fOBro77+sGJkQ9
        Y50RRNYROSEgsndO9xSQa8yfqgwfGy9orQwP6SBDsY8fT9KuZza5CiwZ0utig9l7
        HaRynY3jm7/K1Du5xLjZ/+Hoji76vjAqogIJv/FXFrqXjcJMt1bZcrkxPsZfWHgg
        uMOUZV4WjEv+MCo3sVavPgtS9oscZw9hVlMBAcF42L/F1CkdAT1g0BIaj8gw7U9N
        pMI=
        -----END CERTIFICATE-----
- name: iot-lora-cra-cache
  type: git
  source:
    uri: https://hndocker.oksystem.local/gitlab/IoT/iot-lora-cra-cache.git
    skip_ssl_verification: true
    branch: master

jobs:
- name: build
  plan:
  - get: iot-lora-cra-cache  
  - task: build
    file: iot-lora-cra-cache/ci/build.yml
  - put: iot-lora-cra-cache-registry
    params:
      build: iot-lora-cra-cache 
    attempts: 1  