---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "Simple API"
paths:
  /:
    get:
      operationId: "rootGET"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Pok"
definitions: {}
